### ISSUE TITLE
Currently Not Compatible With Atom 1.0.0

### ISSUE THREAD

**Issue by matthewfarlymn** [yujinakayama/atom-lint#175]
Installing atom-lint to /Users/Matthew/.atom/packages ✗
No available version compatible with the installed Atom version: 1.0.0

**Comment by anjishnu** [comment]
No available version compatible with the installed Atom version: 1.0.2

Is this going to be fixed?

**Comment by perlun** [comment]
Still the same (Atom now at 1.0.5).

**Comment by cclamb** [comment]
ditto 1.0.9

**Comment by dgilperez** [comment]
+1

**Comment by jhmarina** [comment]
same for 1.0.19, any chance of an update?

**Comment by wjdhamilton** [comment]
+1

**Comment by matthewfarlymn** [comment]
Doesn't look like this repository is receiving support anymore.
