### ISSUE TITLE
Add coffee-lint?

### ISSUE THREAD

**Issue by bobrocke** [yujinakayama/atom-lint#65]
Are you planning to add coffee-lint?

Or is it as simple as addition the coffee-lint binary to .atom/packages/atom-lint/lib/linter ?

**Comment by wjn** [comment]
I have the same issue. CoffeeLint is installed. When I save a `.coffee` file, I get the "CoffeeLint is not installed" message. I have this problem with other linters, so my guess is that it's something with Atom rather than the plugins.
